### ISSUE TITLE
404 / missing pages in documentation

### ISSUE THREAD

**Issue by fuunnx** [wejs/docs#1]
http://wejs.org/docs/we/features.admin => error 404
http://wejs.org/docs/we/features.responseformaters => empty page

**Comment by leonanluppi** [comment]
Hello @Funx thank for your reply. I updated the docs and we are working to update wejs site.

**Comment by albertosouza** [comment]
Related to https://github.com/wejs/we/issues/62

**Comment by albertosouza** [comment]
Done.
